server:
  port: 91
  servlet:
    context-path: /client

spring:
  security:
    user:
      password: none
  resources:
    static-locations:
      - classpath:/static/
      - classpath:/templates/
  thymeleaf:
    cache: false

security:
  oauth2:
    client:
      client-id: test1
      client-secret: 123456
      access-token-uri: http://localhost:90/oauth/token
      user-authorization-uri: http://localhost:90/oauth/authorize
    resource:
      jwt:
        key-value: 123456

logging:
  level:
    org.springframework.security: debug
