server:
  port: 8080

spring:
  profiles:
    include:
      - hystrix-default
  application:
    name: hystrix-web

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

management:
  endpoint:
    web:
      exposure:
        include: '*'
logging:
  level:
    org.example.hystrix.api: DEBUG
