server:
  servlet:
    context-path: /
  port: 90

spring:
  resources:
    static-locations:
      - classpath:/static/
      - classpath:/templates/
  thymeleaf:
    cache: false

#logging:
#  level:
#    org.springframework.security: debug
