server:
  servlet:
    context-path: /
  port: 90

spring:
  thymeleaf:
    cache: false
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0

logging:
  level:
    org.springframework.security: debug
